import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRight, Check, ChevronDown, Code2, Code2 as Github, Cookie, ExternalLink, Globe2, Languages, LockKeyhole, Menu, PackageCheck, Play, Server, Settings2, ShieldCheck, X, Zap } from 'lucide-react';
import OpenConsent from '@openconsent/web';
import { createGoogleBusinessExample, type GoogleBusinessStatus } from './google-business-example';
import { sitePolicy } from './site-policy';

type Locale = 'en' | 'zh';
type CategoryState = 'required' | 'granted' | 'denied' | 'mixed' | 'unset';
type Snapshot = { choices?: Record<string, 'granted' | 'denied' | 'unset'>; categoryStates?: Record<string, CategoryState>; signals?: { gpc?: boolean }; policyVersion?: string };
type ConsentClient = { getSnapshot(): Snapshot; subscribe(listener: (snapshot?: Snapshot) => void): () => void; evaluate(purposeId: string): { outcome: string }; show?(): void; showSettings(): void; reset(): void; destroy(): void };

const repo = 'https://github.com/noir-hedgehog/openConsent';
const docs = `${repo}/tree/main/docs`;
const gaId = import.meta.env.VITE_GA_MEASUREMENT_ID || '';
const adsId = import.meta.env.VITE_GOOGLE_ADS_ID || '';
const base = import.meta.env.BASE_URL;
const initialGoogleStatus: GoogleBusinessStatus = { configured: false, analyticsConfigured: false, adsConfigured: false, analyticsAllowed: false, adsMeasurementAllowed: false, adsPersonalizationAllowed: false, loaderState: 'not-configured', commands: ['consent · default'] };

const copy = {
  en: {
    nav: ['Product', 'Live demo', 'Transparency', 'SDKs', 'Checks', 'FAQ'], install: 'Install openConsent', demo: 'Try the live demo', github: 'View on GitHub',
    eyebrow: 'FREE · OPEN SOURCE · SELF HOSTED', title: 'Open-source consent management for modern web apps.', subtitle: 'Add a configurable banner, block optional tags, and explain every category, purpose, vendor, and tracker from one transparent SDK.',
    trust: ['Free forever', 'Self-hosted', 'Apache-2.0', 'GDPR + CCPA/CPRA ready'], outcomeTitle: 'The consent layer your product can actually ship.', outcomeBody: 'A small, inspectable runtime that keeps optional processing off until the user decides, while giving people the detail commercial CMPs taught them to expect.',
    outcomes: [['Clear choices', 'Accessible banner and preference center with Consent, Details, and About views.'], ['Tags stay off by default', 'Explicitly registered scripts do not run before the matching purpose is allowed.'], ['Public disclosure', 'Publish categories, purposes, services, vendors, and trackers without exposing personal receipts.']],
    quickEyebrow: 'PLAIN HTML', quickTitle: 'Start with one script tag.', quickBody: 'Point the SDK to a versioned policy file. No hosted dashboard, account, or openConsent runtime service is required.', copyCode: 'Copy', copied: 'Copied', config: 'View the complete catalog example',
    demoEyebrow: 'LIVE RUNTIME', demoTitle: 'This page is the demo.', demoBody: 'The banner, preference center, persistent privacy trigger, category states, and managed first-party example below are running from @openconsent/web.', settings: 'Open privacy choices', reset: 'Reset demo', inspect: 'Inspect the technical playground', categories: 'Category consent state', cookiePresent: 'Preference cookie detected', cookieAbsent: 'No preference cookie',
    state: { required: 'ALWAYS ON', granted: 'ALLOWED', denied: 'DENIED', mixed: 'MIXED', unset: 'NOT CHOSEN' }, gpc: 'Global Privacy Control', gpcBody: 'When detected, sale/share purposes remain denied and cannot be restored by an older choice.',
    businessEyebrow: 'OFFICIAL SITE IMPLEMENTATION', businessTitle: 'How this website controls real Google tags.', businessBody: 'The website subscribes to generic openConsent purpose decisions, writes Consent Mode defaults, and controls its own GA4 and Google Ads code. This adapter is an example used by the official site; it is not built into the SDK.',
    ga: 'Google Analytics 4', ads: 'Google Ads', configured: 'Configured', waiting: 'Waiting for official asset ID', loaded: 'Tag loaded', blocked: 'No Google request', analyticsChoice: 'Analytics choice', marketingChoice: 'Marketing choices', commandLog: 'Consent Mode command order', noConversion: 'The Ads example initializes the official tag only. It never sends a fake conversion.', declaration: 'Open the public Cookie Declaration',
    transparencyEyebrow: 'PUBLIC DISCLOSURE', transparencyTitle: 'From a category to the exact tracker.', transparencyBody: 'Every disclosed item is versioned with the policy. People can inspect the purpose, service, vendor, storage type, domain, duration, and privacy policy before making a choice.', purposes: 'purposes', services: 'services', trackers: 'trackers', fullDeclaration: 'View the complete Cookie Declaration',
    sdkEyebrow: 'ONE PURPOSE MODEL', sdkTitle: 'Use the same decision everywhere.', sdkBody: 'Framework components present the catalog. Server adapters evaluate the same purpose-level choices and GPC signal before protected work runs.',
    checksEyebrow: 'PRIVACY READINESS CHECKS', checksTitle: 'Deterministic checks your CI can enforce.', checksBody: 'The web-cmp profile checks whether a project has categories, disclosures, vendors, services, and trackers. It produces reviewable JSON and a failing exit code without pretending to be legal certification.', checksPass: 'Catalog valid · 0 blocking · 3 manual review', checksCta: 'See the rules and schema',
    transparentTitle2: 'Keep the rules and the limits visible.', transparentBody2: 'Self-host the runtime, inspect every rule, and keep policy versions with the code that depends on them. openConsent does not receive your users’ consent data.', transparent: ['No cloud dependency', 'Versioned disclosure catalog', 'No openConsent tracking service', 'Public rules and changelog'],
    roadmapTitle: 'A public roadmap, including what is still missing.', roadmapBody: 'Automatic scanning, hosted consent logs, geolocation, IAB certification, a vendor database, and an admin console are not shipped today. Follow the public path from 0.4 to the 1.0 research track.', roadmapCta: 'View product vision and roadmap',
    faqTitle: 'Clear product boundaries.', faqs: [['Does this make my site legally compliant?', 'No library can certify compliance. openConsent supplies controls and transparent disclosures; your purposes, notices, vendors, and legal bases still require review.'], ['Does it automatically find every cookie?', 'No. Version 0.4 blocks and discloses scripts you explicitly register. Automatic scanning and classification are planned for 0.6.'], ['Is Google support built into the SDK?', 'No. The official website demonstrates how an application can subscribe to generic purpose decisions and control its own Google tags.'], ['Is this equivalent to Cookiebot or OneTrust?', 'Not yet. The public catalog and preference experience cover the transparency layer, while scanning, hosted consent evidence, geolocation, IAB frameworks, vendor databases, and admin workflows remain roadmap work.']],
    communityTitle: 'Ship a consent layer people can inspect.', communityBody: 'Use it free, self-host it, and help improve the public rules for modern AI and SaaS products.', docs: 'Read the docs', footer: 'Open-source consent infrastructure for AI and SaaS teams.', privacy: 'Privacy choices', legal: 'Not legal advice.', roadmap: 'Roadmap', cookieDeclaration: 'Cookie Declaration'
  },
  zh: {
    nav: ['产品', '在线演示', '透明披露', 'SDK', '检查', 'FAQ'], install: '安装 openConsent', demo: '体验在线演示', github: '在 GitHub 查看',
    eyebrow: '永久免费 · 开源 · 自托管', title: '面向现代 Web 应用的开源同意管理。', subtitle: '用一个透明 SDK 接入可配置 Banner、可选标签阻断，并清楚说明每个分类、用途、供应商和 Tracker。',
    trust: ['永久免费', '自托管', 'Apache-2.0', '面向 GDPR + CCPA/CPRA'], outcomeTitle: '一个真正能随产品上线的同意层。', outcomeBody: '体积小、规则可检查；用户决定前关闭可选处理，并提供商业 CMP 已经建立的透明度体验。',
    outcomes: [['清晰的选择', '可访问的 Banner 和 Consent、Details、About 三层偏好中心。'], ['默认不运行可选标签', '显式注册的脚本只在对应用途获准后执行。'], ['公开披露', '公开分类、用途、服务、供应商和 Tracker，不暴露个人 receipt。']],
    quickEyebrow: '原生 HTML', quickTitle: '从一行 script 开始。', quickBody: '让 SDK 读取版本化策略文件，无需托管控制台、账户或 openConsent 云端运行服务。', copyCode: '复制', copied: '已复制', config: '查看完整 Catalog 示例',
    demoEyebrow: '真实运行时', demoTitle: '这个页面本身就是演示。', demoBody: '下方 Banner、偏好中心、持续隐私入口、分类状态和第一方受管标签都由 @openconsent/web 真实运行。', settings: '打开隐私选择', reset: '重置演示', inspect: '查看技术 Playground', categories: '分类同意状态', cookiePresent: '检测到偏好 Cookie', cookieAbsent: '没有偏好 Cookie',
    state: { required: '始终开启', granted: '已允许', denied: '已拒绝', mixed: '部分允许', unset: '尚未选择' }, gpc: 'Global Privacy Control', gpcBody: '检测到 GPC 时，出售/共享用途保持拒绝，旧选择也不能重新开启。',
    businessEyebrow: '官网示例实现', businessTitle: '这个官网如何控制真实 Google 标签。', businessBody: '官网订阅 openConsent 的通用 purpose 决定，自行写入 Consent Mode 默认值并控制 GA4 与 Google Ads。这是官网使用的业务示例，不是 SDK 内置功能。',
    ga: 'Google Analytics 4', ads: 'Google Ads', configured: '已配置', waiting: '等待正式资产 ID', loaded: '标签已加载', blocked: '没有 Google 请求', analyticsChoice: '分析用途选择', marketingChoice: '营销用途选择', commandLog: 'Consent Mode 命令顺序', noConversion: 'Ads 示例只初始化正式标签，绝不会发送虚假转化。', declaration: '打开公开 Cookie Declaration',
    transparencyEyebrow: '公开披露', transparencyTitle: '从分类一直查看到具体 Tracker。', transparencyBody: '所有披露内容与策略一起版本化。用户可以在选择前查看用途、服务、供应商、存储类型、域、期限和隐私政策。', purposes: '个用途', services: '个服务', trackers: '个 Tracker', fullDeclaration: '查看完整 Cookie Declaration',
    sdkEyebrow: '统一 PURPOSE 模型', sdkTitle: '在所有技术栈使用同一个决定。', sdkBody: '框架组件负责呈现 Catalog；服务端适配器在受保护处理发生前评估同一份 purpose 选择和 GPC 信号。',
    checksEyebrow: 'PRIVACY READINESS CHECKS', checksTitle: 'CI 可以强制执行的确定性检查。', checksBody: 'web-cmp profile 检查项目是否提供分类、披露、供应商、服务和 Tracker，输出可审查 JSON 与失败退出码，不冒充法律认证。', checksPass: 'Catalog 有效 · 0 个阻断 · 3 项人工复核', checksCta: '查看规则和 Schema',
    transparentTitle2: '让规则和当前边界都保持公开。', transparentBody2: '自行托管运行时，检查每条规则，并让策略版本跟随依赖它的代码。openConsent 不会接收用户同意数据。', transparent: ['无云端依赖', '版本化披露 Catalog', '没有 openConsent 跟踪服务', '公开规则和 Changelog'],
    roadmapTitle: '公开 Roadmap，也公开还缺什么。', roadmapBody: '自动扫描、托管 consent log、geolocation、IAB 认证、供应商数据库和管理后台目前都未交付。Roadmap 会公开从 0.4 到 1.0 research 的推进路径。', roadmapCta: '查看产品愿景与 Roadmap',
    faqTitle: '清晰的产品边界。', faqs: [['它能让网站自动合法合规吗？', '不能。openConsent 提供控制和透明披露；你的用途、notice、供应商和法律基础仍需专业审查。'], ['它会自动发现所有 Cookie 吗？', '不会。0.4 阻断并披露你显式注册的脚本；自动扫描和分类计划在 0.6 推进。'], ['Google 支持是 SDK 内置的吗？', '不是。官网示范应用如何订阅通用 purpose 决定，并自行控制 Google 标签。'], ['它已经等同 Cookiebot 或 OneTrust 吗？', '还没有。公开 Catalog 和偏好体验补齐透明层；扫描、托管证据、区域识别、IAB、供应商数据库和后台仍在 Roadmap。']],
    communityTitle: '上线一个用户也能检查的同意层。', communityBody: '免费使用、自行托管，并参与完善适合现代 AI 与 SaaS 产品的公开规则。', docs: '阅读文档', footer: '面向 AI 与 SaaS 团队的开源同意基础设施。', privacy: '隐私选择', legal: '不构成法律意见。', roadmap: 'Roadmap', cookieDeclaration: 'Cookie Declaration'
  }
} as const;

const scriptSnippet = `<script\n  src="https://noir-hedgehog.github.io/openConsent/openconsent.min.js"\n  data-openconsent-config="/openconsent.json">\n</script>`;
const sdkSnippets = {
  React: `import { OpenConsentProvider, ConsentBanner } from '@openconsent/react';\n\n<OpenConsentProvider options={{ policy }}>\n  <App />\n  <ConsentBanner locale="en" />\n</OpenConsentProvider>`,
  Vue: `app.use(createOpenConsentPlugin({ policy }))\n\n<ConsentBanner locale="en" />\n// useOpenConsent() anywhere`,
  Express: `app.use(openConsent({ policy, getSnapshot }))\napp.post('/analytics',\n  requirePurpose('site-analytics'), handler)`,
  Spring: `OpenConsentDecision result = evaluator.evaluate(\n  "site-analytics", receipt.policyVersion(), gpc, choices\n);`
};
const localized = (value: string | { en: string; zh?: string }, locale: Locale) => typeof value === 'string' ? value : value[locale] || value.en;

export default function App() {
  const [locale, setLocale] = useState<Locale>(() => localStorage.getItem('openconsent_site_locale') === 'zh' ? 'zh' : 'en');
  const [mobile, setMobile] = useState(false);
  const [copied, setCopied] = useState(false);
  const [sdk, setSdk] = useState<keyof typeof sdkSnippets>('React');
  const [snapshot, setSnapshot] = useState<Snapshot>({ categoryStates: { necessary: 'required', preferences: 'unset', analytics: 'unset', marketing: 'unset' } });
  const [googleStatus, setGoogleStatus] = useState<GoogleBusinessStatus>(initialGoogleStatus);
  const [cookieRevision, setCookieRevision] = useState(0);
  const clientRef = useRef<ConsentClient | null>(null);
  const t = copy[locale];

  useEffect(() => {
    document.documentElement.lang = locale === 'zh' ? 'zh-CN' : 'en';
    localStorage.setItem('openconsent_site_locale', locale);
    const client = OpenConsent.init({ projectId: 'openconsent-site', locale, policy: sitePolicy as never, banner: { position: 'bottom', theme: 'auto', privacyPolicyUrl: `${repo}/blob/main/docs/TRANSPARENCY.md` }, onPreferenceChange: () => setSnapshot(client.getSnapshot()) }) as ConsentClient;
    clientRef.current = client;
    queueMicrotask(() => setSnapshot(client.getSnapshot()));
    const unsubscribe = client.subscribe(next => setSnapshot(next ?? client.getSnapshot()));
    const google = createGoogleBusinessExample(client, { measurementId: gaId, adsTagId: adsId, onChange: setGoogleStatus });
    return () => { google.destroy(); unsubscribe(); client.destroy(); if (clientRef.current === client) clientRef.current = null; };
  }, [locale]);

  useEffect(() => { const refresh = () => setCookieRevision(value => value + 1); window.addEventListener('openconsent:vendor-loaded', refresh); return () => window.removeEventListener('openconsent:vendor-loaded', refresh); }, []);
  const categoryRows = useMemo(() => sitePolicy.categories.map(category => ({ ...category, labelText: localized(category.label, locale), purposeCount: sitePolicy.purposes.filter(purpose => purpose.categoryId === category.id).length, state: snapshot.categoryStates?.[category.id] ?? (category.required ? 'required' : 'unset') })), [locale, snapshot.categoryStates]);
  void cookieRevision;
  const hasPreferenceCookie = document.cookie.split(';').some(item => item.trim().startsWith('oc_demo_preferences='));
  const scrollTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMobile(false); };
  const copyInstall = async () => { await navigator.clipboard.writeText(scriptSnippet); setCopied(true); window.setTimeout(() => setCopied(false), 1500); };
  const resetDemo = () => { clientRef.current?.reset(); clientRef.current?.show?.(); setSnapshot(clientRef.current?.getSnapshot() ?? {}); };
  const googleCardState = (configured: boolean, active: boolean) => configured ? (active ? t.loaded : t.blocked) : t.waiting;

  return <div className="site-shell">
    <header className="nav-wrap"><nav className="nav" aria-label="Main navigation"><a className="brand" href="#top"><span className="brand-mark"><ShieldCheck size={18}/></span><span>openConsent</span></a><div className={`nav-links ${mobile ? 'open' : ''}`}>{['product', 'demo', 'transparency', 'sdks', 'checks', 'faq'].map((id, index) => <button key={id} onClick={() => scrollTo(id)}>{t.nav[index]}</button>)}</div><div className="nav-actions"><button className="language" onClick={() => setLocale(locale === 'en' ? 'zh' : 'en')} aria-label="Switch language"><Languages size={16}/>{locale === 'en' ? '中文' : 'EN'}</button><a className="nav-github" href={repo} target="_blank" rel="noreferrer"><Github size={17}/><span>GitHub</span></a><button className="menu" onClick={() => setMobile(!mobile)} aria-label="Toggle navigation">{mobile ? <X/> : <Menu/>}</button></div></nav></header>
    <main id="top">
      <section className="hero section-grid"><div className="hero-copy"><div className="eyebrow"><span className="pulse"/>{t.eyebrow}</div><h1>{t.title}</h1><p className="hero-subtitle">{t.subtitle}</p><div className="hero-actions"><button className="primary" onClick={() => scrollTo('quickstart')}>{t.install}<ArrowRight size={18}/></button><button className="secondary" onClick={() => { scrollTo('demo'); clientRef.current?.show?.(); }}><Play size={17}/>{t.demo}</button></div><div className="trust-row">{t.trust.map(item => <span key={item}><Check size={14}/>{item}</span>)}</div></div><div className="hero-product-card"><div className="window-bar"><span/><span/><span/><small>your-app.example</small></div><div className="mini-app"><div className="mini-nav"/><div className="mini-content"><div className="mini-kicker"/><div className="mini-title"/><div className="mini-line"/><div className="mini-line short"/></div><div className="mini-banner"><div className="mini-shield"><ShieldCheck/></div><div><strong>We respect your privacy</strong><p>Review categories, purposes, services and trackers.</p></div><div className="mini-buttons"><span>Reject optional</span><b>Manage choices</b></div></div></div><div className="floating-proof proof-one"><LockKeyhole size={16}/><span>0 optional requests</span></div><div className="floating-proof proof-two"><Cookie size={16}/><span>4 categories · 7 trackers</span></div></div></section>
      <section id="product" className="section product-section"><div className="section-intro"><h2>{t.outcomeTitle}</h2><p>{t.outcomeBody}</p></div><div className="feature-grid">{t.outcomes.map(([title, body], index) => { const Icon = [ShieldCheck, Zap, Globe2][index]; return <article key={title}><div className="icon-box"><Icon/></div><h3>{title}</h3><p>{body}</p></article>; })}</div></section>
      <section id="quickstart" className="section split-section"><div><div className="eyebrow">{t.quickEyebrow}</div><h2>{t.quickTitle}</h2><p>{t.quickBody}</p><a className="text-link" href={`${repo}/blob/main/examples/openconsent.web.json`} target="_blank" rel="noreferrer">{t.config}<ArrowRight size={16}/></a></div><div className="code-card"><div className="code-head"><span>index.html</span><button onClick={copyInstall}>{copied ? <Check/> : <Code2/>}{copied ? t.copied : t.copyCode}</button></div><pre><code>{scriptSnippet}</code></pre></div></section>
      <section id="demo" className="section demo-section"><div className="demo-copy"><div className="eyebrow">{t.demoEyebrow}</div><h2>{t.demoTitle}</h2><p>{t.demoBody}</p><div className="demo-actions"><button className="primary small" onClick={() => clientRef.current?.showSettings()}><Settings2 size={17}/>{t.settings}</button><button className="secondary small" onClick={resetDemo}>{t.reset}</button></div><a className="text-link" href={`${base}playground/`}>{t.inspect}<ArrowRight size={16}/></a></div><div className="runtime-card"><div className="runtime-head"><div><span className="live-dot"/>{t.categories}</div><small>policy {snapshot.policyVersion ?? sitePolicy.policyVersion}</small></div>{categoryRows.map(row => <div className="runtime-row" key={row.id}><div className="purpose-icon"><Cookie/></div><div className="runtime-name"><strong>{row.labelText}</strong><small>{row.purposeCount} {t.purposes}</small></div><div className="runtime-cookie">{row.id === 'preferences' ? (hasPreferenceCookie ? t.cookiePresent : t.cookieAbsent) : row.id}</div><span className={`status ${row.state}`}>{t.state[row.state]}</span></div>)}<div className="gpc-row"><div><strong>{t.gpc}</strong><p>{t.gpcBody}</p></div><span className={snapshot.signals?.gpc ? 'signal on' : 'signal'}>{snapshot.signals?.gpc ? 'ON' : 'OFF'}</span></div></div></section>
      <section className="section business-example"><div className="center-intro"><div className="eyebrow">{t.businessEyebrow}</div><h2>{t.businessTitle}</h2><p>{t.businessBody}</p></div><div className="business-grid"><article><div className="business-card-head"><div className="google-logo">G<span>A</span></div><span className={googleStatus.analyticsConfigured ? 'config-state ready' : 'config-state'}>{googleStatus.analyticsConfigured ? t.configured : t.waiting}</span></div><h3>{t.ga}</h3><p>{t.analyticsChoice}: <b>{snapshot.categoryStates?.analytics ? t.state[snapshot.categoryStates.analytics] : t.state.unset}</b></p><strong className={googleStatus.analyticsAllowed ? 'request-state loaded' : 'request-state'}>{googleCardState(googleStatus.analyticsConfigured, googleStatus.analyticsAllowed)}</strong></article><article><div className="business-card-head"><div className="google-logo ads">G<span>Ads</span></div><span className={googleStatus.adsConfigured ? 'config-state ready' : 'config-state'}>{googleStatus.adsConfigured ? t.configured : t.waiting}</span></div><h3>{t.ads}</h3><p>{t.marketingChoice}: <b>{snapshot.categoryStates?.marketing ? t.state[snapshot.categoryStates.marketing] : t.state.unset}</b></p><strong className={googleStatus.adsMeasurementAllowed ? 'request-state loaded' : 'request-state'}>{googleCardState(googleStatus.adsConfigured, googleStatus.adsMeasurementAllowed)}</strong></article></div><div className="command-card"><div><LockKeyhole size={18}/><strong>{t.commandLog}</strong></div><code>{googleStatus.commands.join(' → ')}</code><small>{t.noConversion}</small></div><a className="text-link centered" href={`${base}cookie-declaration/`}>{t.declaration}<ArrowRight size={16}/></a></section>
      <section id="transparency" className="section catalog-section"><div className="section-intro"><div className="eyebrow">{t.transparencyEyebrow}</div><h2>{t.transparencyTitle}</h2><p>{t.transparencyBody}</p></div><div className="catalog-grid">{sitePolicy.categories.map(category => { const purposeIds = sitePolicy.purposes.filter(purpose => purpose.categoryId === category.id).map(purpose => purpose.id); const services = sitePolicy.services.filter(service => service.purposeIds.some(id => purposeIds.includes(id as never))); const trackers = sitePolicy.trackers.filter(tracker => tracker.purposeIds.some(id => purposeIds.includes(id as never))); return <article key={category.id}><span className={category.required ? 'category-chip required' : 'category-chip'}>{category.required ? t.state.required : t.state.unset}</span><h3>{localized(category.label, locale)}</h3><p>{localized(category.description, locale)}</p><div className="catalog-counts"><span>{purposeIds.length} {t.purposes}</span><span>{services.length} {t.services}</span><span>{trackers.length} {t.trackers}</span></div></article>; })}</div><a className="text-link" href={`${base}cookie-declaration/`}>{t.fullDeclaration}<ArrowRight size={16}/></a></section>
      <section id="sdks" className="section sdk-section"><div className="section-intro"><div className="eyebrow">{t.sdkEyebrow}</div><h2>{t.sdkTitle}</h2><p>{t.sdkBody}</p></div><div className="sdk-workbench"><div className="sdk-tabs">{Object.keys(sdkSnippets).map(name => <button className={sdk === name ? 'active' : ''} onClick={() => setSdk(name as keyof typeof sdkSnippets)} key={name}>{name}</button>)}</div><div className="sdk-code"><pre><code>{sdkSnippets[sdk]}</code></pre></div><div className="sdk-flow"><div><span>01</span><b>Catalog</b><small>categories + disclosures</small></div><ArrowRight/><div><span>02</span><b>Purpose decision</b><small>consent + GPC</small></div><ArrowRight/><div><span>03</span><b>Gate</b><small>browser or server</small></div></div></div></section>
      <section id="checks" className="section checks-section"><div className="checks-terminal"><div className="terminal-head"><span/><span/><span/><small>openconsent check --profile web-cmp</small></div><pre><code><span className="prompt">$</span> openconsent check ./openconsent.json --profile web-cmp{`\n\n`}<span className="pass">PASS CMP-001</span> Consent categories declared{`\n`}<span className="pass">PASS CMP-002</span> Services map to known vendors{`\n`}<span className="pass">PASS CMP-003</span> Trackers map to declared purposes{`\n`}<span className="warn">REVIEW GDPR-002</span> Withdrawal route{`\n\n`}<b>{t.checksPass}</b></code></pre></div><div className="checks-copy"><div className="eyebrow">{t.checksEyebrow}</div><h2>{t.checksTitle}</h2><p>{t.checksBody}</p><a className="text-link" href={`${repo}/tree/main/rules`} target="_blank" rel="noreferrer">{t.checksCta}<ArrowRight size={16}/></a></div></section>
      <section className="section transparent-section"><div><div className="icon-box"><Server/></div><h2>{t.transparentTitle2}</h2><p>{t.transparentBody2}</p></div><div className="transparency-list">{t.transparent.map(item => <div key={item}><Check/><span>{item}</span></div>)}</div></section>
      <section className="section roadmap-teaser"><div><div className="eyebrow">PUBLIC ROADMAP</div><h2>{t.roadmapTitle}</h2><p>{t.roadmapBody}</p></div><a className="primary" href={`${base}roadmap/`}>{t.roadmapCta}<ArrowRight size={17}/></a></section>
      <section id="faq" className="section faq-section"><div className="section-intro"><h2>{t.faqTitle}</h2></div><div className="faq-list">{t.faqs.map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown/></summary><p>{answer}</p></details>)}</div></section>
      <section className="section community"><div><PackageCheck/><h2>{t.communityTitle}</h2><p>{t.communityBody}</p><div className="hero-actions"><a className="primary" href={repo} target="_blank" rel="noreferrer"><Github/>{t.github}<ExternalLink size={15}/></a><a className="secondary" href={docs} target="_blank" rel="noreferrer">{t.docs}</a></div></div></section>
    </main>
    <footer><div><a className="brand" href="#top"><span className="brand-mark"><ShieldCheck size={18}/></span><span>openConsent</span></a><p>{t.footer}</p></div><div className="footer-links"><button onClick={() => clientRef.current?.showSettings()}>{t.privacy}</button><a href={`${base}cookie-declaration/`}>{t.cookieDeclaration}</a><a href={`${base}roadmap/`}>{t.roadmap}</a><a href={docs}>{t.docs}</a><a href={repo}>GitHub</a></div><small>© 2026 openConsent · Apache-2.0 · {t.legal}</small></footer>
  </div>;
}
